name: cicd

on: 
  workflow_dispatch: 
    inputs:
      environments:
        description: This is environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
      

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: "clone the github repo"
        run: echo "code clone from github repo"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: "docker build"
        run: echo "build docker images"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "test the code"
        run: echo "testing the container"

  deploy:
    if: inputs.environments == 'prod'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: "deplot the code"
        run: echo "docker compose up"
