name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker compose
        uses: docker/setup-compose-action@v2

      - name: Pull latest image
        run: docker compose pull

      - name: Deploy latest container
        run: docker compose up -d --force-recreate

      - name: Show running containers
        run: docker compose ps

      - name: Check app health
        run: curl --fail http://localhost/health
