name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy with docker compose
              env:
                DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
              run: |
                docker compose down || true
                docker compose up -d --build
                docker compose ps
                docker compose logs