name: hello!!

# run on a trigger!!
on:
  push:
    branches: [main]
 # only trigger when any changes occur in html file!!
    paths:
      - '**.html'

# These are jobs inside workflow!!
jobs:
# name of jobs!!
  greet:
# ubuntu github runner!!
    runs-on: ubuntu-latest
    steps:
      - name: say hello to friends!!
        run: echo "Hello friends"
      - name: say hello to username
        run: echo "hello $USER"

  details:
    needs: [greet]
    runs-on: ubuntu-latest
    steps:
      - name: show that versions of python && docker!!
        run: docker --version && python --version
              
