name: portfolio

on:
  workflow_dispatch: 
      
permissions: 
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # actions/checkout@v4 copies your GitHub repository into that machine called runner like ubuntu-latest !!
      
      - name: Setup up github page
        uses: actions/configure-pages@v4  # GitHub Pages is a free hosting service by GitHub that lets you host websites directly from a GitHub repository.
      
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./backend  # you have to need add static file inside backend folder !!
      
      - name: Deploy to github pages
        uses: actions/deploy-pages@v4
